### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array. 

### ISSUE THREAD

**Issue by LacusCon** [hiram3512/HiSocket#10]
IndexOutOfRangeException: Index was outside the bounds of the array. 
HiFramework.CircularBuffer`1[T].Write (T[] array) (at Assets/ThirdPlugin/HiSocket/TcpConnection/Socket/CircalBuffer.cs:166) 
HiSocket.TcpSocket.Send (System.Byte[] bytes) (at Assets/ThirdPlugin/HiSocket/TcpConnection/Socket/TcpSocket.cs:171)
HiSocket.TcpConnection.m__0 (System.Byte[] x) (at Assets/ThirdPlugin/HiSocket/TcpConnection/TcpConnection.cs:62)

**Comment by hiramtan** [comment]
You should reset your buffer's storage to more bigger size

**Comment by hiram3512** [comment]
Download the newest logic and check if still have this question.
I have commited some new logic to this repository

**Comment by LacusCon** [comment]
> Download the newest logic and check if still have this question.
> I have commited some new logic to this repository

thx  for your reply.I will try it later.

**Comment by LacusCon** [comment]
> Download the newest logic and check if still have this question.
> I have commited some new logic to this repository
更新后不能正常的通信

**Comment by hiram3512** [comment]
下载最新的2.7.4版本:https://github.com/hiramtan/HiSocket/releases
昨天的改动导致单元测试不能通过.
现在修改了逻辑,单元测试通过.
