### ISSUE TITLE
while closing the scene it gives an error on socket.close method

### ISSUE THREAD

**Issue by shubhamguptak** [hiram3512/HiSocket#11]
NullReferenceException: Object reference not set to an instance of an object
Example.OnApplicationQuit () (at Assets/Example/Example.cs:75)
 
//Code
void OnApplicationQuit()
    {
        _tcp.Dispose();
        _server.Close(); //Here it is giving error line 75
    }

**Comment by hiram3512** [comment]
This is a test server only used for testing HiSocket's logic, you can ignore this error.
Next version will fix this bug.
