### ISSUE TITLE
OnDisconnected event has problem

### ISSUE THREAD

**Issue by wolforce** [hiram3512/HiSocket#13]
![hisocket_disconnect_bug](https://user-images.githubusercontent.com/1756757/64801197-9f044000-d5ba-11e9-8bbf-93d879269b41.png)

when i close server application, client can not receive the OnDisconnected event.
it seems some thing wrong with `TcpSocket.cs` on line 268.
when server close, it trigger an exception on line 262, then the TcpSocket catch but throw it away.
thus `DisconnectedEvnet()` on line 280 will never be invoke.

**Comment by hiram3512** [comment]
thanks for your feedback, check this issue and tcp protocol recommend  is use heart beat to check connection, or you can trigger disconnect event when you catch exception.
https://github.com/hiramtan/HiSocket/issues/1#issuecomment-377866504
