### ISSUE TITLE
这个socket客户端解决方案，是否支持udp？

### ISSUE THREAD

**Issue by Ferrarie** [hiram3512/HiSocket#15]
简单阅读了文档和案例，没找到关于udp传输的相关功能

**Comment by hiram3512** [comment]
不支持udp,非可靠udp传输协议很简单可以自己实现,可靠udp传输建议采用其他开源方案实现

**Comment by Ferrarie** [comment]
感谢回复，关于可靠udp传输方面，我会寻找另外的解决方案

**Comment by midgithub** [comment]
如果不准备继续支持了。可以把相关的tag去掉

**Comment by hiram3512** [comment]
> 如果不准备继续支持了。可以把相关的tag去掉

已移除udp相关标签
