### ISSUE TITLE
使用 TcpConnection.Connect()没有反应结果，如何捕获连接的异常？

### ISSUE THREAD

**Issue by WengJianyang** [hiram3512/HiSocket#16]

**Comment by hiram3512** [comment]
直接使用trycatch捕获这个接口的异常即可

**Comment by WengJianyang** [comment]
> 直接使用trycatch捕获这个接口的异常即可

有一种情况没有走进异常情况，也没捕获异常，有链接超时接口吗

**Comment by WengJianyang** [comment]
> 直接使用trycatch捕获这个接口的异常即可

我使用connect链接一个地址，什么反应都没有，后来发现是地址输错了，然后我想在这里加一个回调，例如连接超时或者地址不存在的异常以做提醒

**Comment by hiram3512** [comment]
> > 直接使用trycatch捕获这个接口的异常即可
> 
> 我使用connect链接一个地址，什么反应都没有，后来发现是地址输错了，然后我想在这里加一个回调，例如连接超时或者地址不存在的异常以做提醒

连接超时用系统的timeout,系统会在连接是抛出各种异常,可以通过connect接口捕获到

**Comment by WengJianyang** [comment]
你说的这个系统的timeout具体是指哪个？可以给一个链接吗

**Comment by hiram3512** [comment]
> 你说的这个系统的timeout具体是指哪个？可以给一个链接吗

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.sendtimeout?redirectedfrom=MSDN&view=netframework-4.8#System_Net_Sockets_TcpClient_SendTimeout


https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.tcpclient.receivetimeout?redirectedfrom=MSDN&view=netframework-4.8#System_Net_Sockets_TcpClient_ReceiveTimeout

收发，连接...都有超时设置，查下官方文档

**Comment by WengJianyang** [comment]
收发能看到，但是链接没有。。。

**Comment by hiram3512** [comment]
> 收发能看到，但是链接没有。。。

connect系统有默认的超时时间，等待超时后抛出异常，如果不想等待那么久自己写逻辑处理超时，源码里面有提供socket对象，可以对它进行操作，比如：
https://stackoverflow.com/questions/1062035/how-to-configure-socket-connect-timeout

多查下资料，这种网上方案很多..

**Comment by lookforit** [comment]
> 直接使用trycatch捕获这个接口的异常即可

我看了下源码，connect()方法最终调用了BeginConnect()。
由于异常在asynccallback 中最终被抛出，导致在主线程无法捕获。

请问如何处理

**Comment by hiram3512** [comment]
> asynccallback

既然异常在asynccallback中被抛出,可以在callback中捕获异常做对应的处理.
