### ISSUE TITLE
使用TcpConnection一次性接收16000bit的数据时候报异常

### ISSUE THREAD

**Issue by WengJianyang** [hiram3512/HiSocket#17]
你好

**Comment by JYheartworld** [comment]
有什么API可以设置接收缓存池的大小吗

**Comment by WengJianyang** [comment]
> 你好

我这边使用TCPConnection进行接收服务器的消息，服务器一次性给我发送16000bit数据的时候，客户端TcpConnection会出现断开的情况，出现这个问题的时候我要怎么处理？

**Comment by hiram3512** [comment]
服务器发送的消息包的大小，不会导致客户端连接断开，捕获一下接收消息的逻辑看是否有异常，然后捕获一下断开连接的逻辑看哪里引发的。

**Comment by WengJianyang** [comment]
> 服务器发送的消息包的大小，不会导致客户端连接断开，捕获一下接收消息的逻辑看是否有异常，然后捕获一下断开连接的逻辑看哪里引发的。

谢谢解决了，是遇到拆包的问题

**Comment by WengJianyang** [comment]
你好，这边对tcpconnection还遇到一个问题，正常情况下，这个是tcpconnection是会由客户端或者服务端主动断开的。但除了两个情况之外还有另外一种情况，我每间隔一段时间去访问Tcpconnection.IsConnected，发现会出现报空的情况，请问我这个情况问题会出在哪里？有没有常见问题的FAQ？

**Comment by hiramtan** [comment]
1.isConnect值类型不会报空，报空只会是socket对象判定，判定逻辑也是按照socket，socket.isconnet顺序，不存在你说的这种情况，建议捕获异常查一下是不是其他异常导致。
2.场景异常在issue里面查找
3.建议查一下socket相关资料

**Comment by hiram3512** [comment]
> 你好，这边对tcpconnection还遇到一个问题，正常情况下，这个是tcpconnection是会由客户端或者服务端主动断开的。但除了两个情况之外还有另外一种情况，我每间隔一段时间去访问Tcpconnection.IsConnected，发现会出现报空的情况，请问我这个情况问题会出在哪里？有没有常见问题的FAQ？

1.isConnect值类型不会报空，报空只会是socket对象判定，判定逻辑也是按照socket，socket.isconnet顺序，不存在你说的这种情况，建议捕获异常查一下是不是其他异常导致。
2.场景异常在issue里面查找
3.建议查一下socket相关资料

**Comment by WengJianyang** [comment]
> > 你好，这边对tcpconnection还遇到一个问题，正常情况下，这个是tcpconnection是会由客户端或者服务端主动断开的。但除了两个情况之外还有另外一种情况，我每间隔一段时间去访问Tcpconnection.IsConnected，发现会出现报空的情况，请问我这个情况问题会出在哪里？有没有常见问题的FAQ？
> 
> 1.isConnect值类型不会报空，报空只会是socket对象判定，判定逻辑也是按照socket，socket.isconnet顺序，不存在你说的这种情况，建议捕获异常查一下是不是其他异常导致。
> 2.场景异常在issue里面查找
> 3.建议查一下socket相关资料

感谢
