### ISSUE TITLE
看起来不错，不知后期是否有融合KCP的打算

### ISSUE THREAD

**Issue by fredshao** [hiram3512/HiSocket#2]

**Comment by hiram3512** [comment]
没有融合kcp的打算,因为:
- 这个项目主要处理tcp协议.
- 和kcp共存,如果项目需要kcp可以引入kcp源码到项目并且和这套逻辑不会有冲突.
- 如果本项目引入kcp也是复制源码做些对接, 并且kcp如果有更新还要维护这部分代码的更新不太方便.
