### ISSUE TITLE
Problema with expections being thrown

### ISSUE THREAD

**Issue by raphaelns-developer** [hiram3512/HiSocket#22]
Hey @hiram3512 ,

First thanks for the project it really helps me a lot, but i want to ask you something: always when an erro occours the error is thrown but i haven't any way to catch this error, maybe you could change this behavior to trigger an error event instead of thrown an error so i can listen to event and do something.

Thanks

**Comment by hiram3512** [comment]
Thanks for feedback. There are so many different exceptions, throw try-catch you can get more useful info and debug them. also you can catch the expected error you want, so I recommend use this way to handle errors.

**Comment by raphaelns-developer** [comment]
The problema is that in some places i don't have access to catch the exception like the method `EndReceive` of the `TcpSocket` class.

**Comment by hiram3512** [comment]
Checkout the new version, have added an exception event in socket logic.
