### ISSUE TITLE
事件不应在异步方法的回调中触发，因为事件的委托基本上要调用UnityEngine的API，而异步方法的回调不是在Unity主线程中执行的。

### ISSUE THREAD

**Issue by DreamOfGod** [hiram3512/HiSocket#24]

**Comment by hiram3512** [comment]
异步触发的问题,其实是非主线程调用Unity Component API的问题.
为了提高效率采用多线程通信,并且和通信相关的,比如封包解包对时加密服务器数据维护等不会涉及到Component的操作.
如果自己的项目确实要数据驱动表现(正确的是表现依赖数据),可以扩展自己的逻辑实现.
很早之前的版本有主线程事件回调/主线程监听其他线程消息转移到主线程,如果有需要可以参考下老版本.
