### ISSUE TITLE
Support reconnect feature in example

### ISSUE THREAD

**Issue by takaaptech** [hiram3512/HiSocket#4]
Hi! @hiramtan 
I just found this code and it is very simple and easy to understand! Thank so much for such an awesome plugin!
I need implement reconnect feature(when user drop by a weak signal or switch from wifi to Mobile Data)
Please add to example how to do that!
Thank so much!

**Comment by hiram3512** [comment]
You can implement this function by yourself, there is a queue of send message, when disconnect to server, you can resend the message in the send queue.

**Comment by hiram3512** [comment]
Maybe will support reconnect and resend remain message in next version. And this function can easily extend by user, just get disconnect event, and resend message again.

**Comment by hiram3512** [comment]
> Hi! @hiramtan
> I just found this code and it is very simple and easy to understand! Thank so much for such an awesome plugin!
> I need implement reconnect feature(when user drop by a weak signal or switch from wifi to Mobile Data)
> Please add to example how to do that!
> Thank so much!

In newest version, add a send buffer. When disconnect with server of exception, user can get the remain haven't send bytes from buffer(old version is get message from send queue) and decide to resend it again or just ignore it.
