### ISSUE TITLE
编辑器卡死

### ISSUE THREAD

**Issue by chu358177** [hiram3512/HiSocket#8]
第二次运行example场景，必卡死。ondestory 内 DisConnect();tcp.Dispose() 也没用。貌似没别的可用的了。unity2018.2.5

**Comment by hiram3512** [comment]
请描述下具体的流程，谢谢：
1.服务器有开启吗？
2.unity客户端是什么状态下关闭的？（连接状态下关闭还是连接中关闭？）
3.有响应客户端成功连接的事件吗？
4.有响应客户端正在连接的事件吗？
5.关闭逻辑确定执行了吗？
6.期间有其他异常抛出吗？

如果没有及时回复，也可以通过邮箱联系，hiramtan@live.com

> 第二次运行example场景，必卡死。ondestory 内 DisConnect();tcp.Dispose() 也没用。貌似没别的可用的了。unity2018.2.5

**Comment by hiram3512** [comment]
> 第二次运行example场景，必卡死。ondestory 内 DisConnect();tcp.Dispose() 也没用。貌似没别的可用的了。unity2018.2.5

已测试在服务器未开启的情况下，unity客户端并没有出现问题。
服务器在开启的情况下：连接成功后断开还是未连接成功下断开导致卡死？

**Comment by chu358177** [comment]
找到问题了，设置为 .net4.X 后就好了

**Comment by hiram3512** [comment]
> 找到问题了，设置为 .net4.X 后就好了

.net 3.5平台也应该不会有问题

**Comment by hiram3512** [comment]
看你把问题关闭了，意思是.net 3.5 也应该没问题吧
