### ISSUE TITLE
StringHexToBytes has problem

### ISSUE THREAD

**Issue by NakedVane** [hiram3512/HiSocket#9]
server received data：
1A 00 00 00 61 75 74 68 65 6E 74 69 63 61 74 65 20 31 0D 0A 6B 69 6C 6C 20 22 31 22 0D 0A
but client send data：
61 75 74 68 65 6E 74 69 63 61 74 65 20 31 0D 0A 6B 69 6C 6C 20 22 31 22 0D 0A

why?

**Comment by NakedVane** [comment]
I've got it, you insert the head data while you pack.

**Comment by hiram3512** [comment]
You can pack and unpack data by yourself, for example add some data in the head.
